name: Assignment Email Cron

on:
  schedule:
    - cron: '0 * * * *' # Setiap jam pada menit ke-0 (UTC)
  workflow_dispatch:

jobs:
  call-assignment-email:
    runs-on: ubuntu-latest
    steps:
      - name: Call assignment email endpoint
        env:
          ASSIGNMENT_CRON_URL: ${{ secrets.ASSIGNMENT_CRON_URL }}
        run: |
          curl -X GET "$ASSIGNMENT_CRON_URL" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"