name: Assignment Email Cron

on:
  schedule:
    - cron: '0 * * * *' # Setiap jam pada menit ke-0 (UTC)
  workflow_dispatch:

jobs:
  call-assignment-email:
    runs-on: ubuntu-latest
    steps:
      - name: Call assignment email endpoint
        run: |
          curl -X GET "https://ciao-pink.vercel.app/api/cron/assignment-email" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"