name: Deadline Email Cron

on:
  schedule:
    - cron: '0 0 * * *' # Setiap hari jam 07:00 WIB (0 0 UTC)
  workflow_dispatch:

jobs:
  call-deadline-email:
    runs-on: ubuntu-latest
    steps:
      - name: Call deadline email endpoint
        run: |
          curl -X GET "https://ciao-pink.vercel.app/api/cron/deadline-email" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"